version: "3"

services:
  # Sevicio para realizar pruebas de llamada a una API
  external-resources-api:
    image: nginx:1.21.0-alpine
    container_name: product-system_external-resources-api
    restart: always
    volumes:
      - ./external-resources/api:/usr/share/nginx/html
    ports:
      - 8088:80
    environment:
      - NGINX_PORT=80

  # Sevicio para realizar pruebas de conexion a un servidor sFTP
  external-resources-ftp:
    image: stilliard/pure-ftpd
    container_name: product-system_external-resources-ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./external-resources/ftp:/home/username
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    restart: always
