version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    container_name: product-system_app
    depends_on:
      - mongo

  nginx:
    image: nginx:1.21.0-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - app

  cron:
    image: docker
    command: crond -f -l 8
    volumes:
      - ./cron-tasks/15min:/etc/periodic/15min/:ro
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:4.4.6
    restart: always
    env_file:
      - ./app/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_password
